[buildPlans.IosevkaCustom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaCustom.variants]
  inherits = "ss12"

    [buildPlans.IosevkaCustom.variants.design]
    zero = "slashed"
    capital-h = "top-left-serifed"
    capital-m = "hanging-motion-serifed"
    capital-q = "curly-tailed"
    capital-w = "curly-serifless"
    f = "narrow-tailed"
    g = "double-storey-open"
    j = "narrow-serifed"
    l = "semi-tailed"
    m = "earless-corner-double-arch-serifed"
    n = "tailed-serifed"
    r = "narrow-hook-top-serifed"
    v = "curly-motion-serifed"
    w = "curly-motion-serifed"
    x = "cursive"
    y = "cursive-motion-serifed"
    lig-neq = "vertical-dotted"

  [buildPlans.IosevkaCustom.ligations]
  inherits = "clike"

[buildPlans.IosevkaCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
